image: node:14-alpine

stages:
    - build
    - deploy

cache:
    paths:
        - node_modules/
        - public/

build:
    stage: build
    script:
        - node --version
        - npm install --silent
        - echo "Building $CI_ENVIRONMENT_NAME"
        - npm run build-ci
    artifacts:
        paths:
            - dist/
            - node_modules/

deploy:
  stage: deploy
  dependencies:
    - build
  only:
    - main
  environment:
    name: development
    url: https://hotel-offers.surge.sh
  script:
    - echo "Deploy public"
    - npm i surge -g
    - npm run deploy
  artifacts:
    paths:
      - public


