image: node:14-alpine

stages:
    - build

cache:
    paths:
        - node_modules/

build:
    stage: build
    script:
        - node --version
        - npm install --silent
        - echo "Building $CI_ENVIRONMENT_NAME"
        - ng build --progress --configuration production
    artifacts:
        paths:
            - dist/
            - node_modules/