image: node:14-alpine

stages:
    - install_dependencies
    - build

cache:
    paths:
        - node_modules/

install_dependencies:
    stage: install_dependencies
    script:
        - node --version
        - npm install --silent
    artifacts:
        paths:
            - node_modules/

build:
    stage: build
    script:
        - echo "Building $CI_ENVIRONMENT_NAME"
        - npm run build
    artifacts:
        paths:
            - dist/
    

